#coding:utf8
str1 = '''
{
  "results": [
    {
      "alternatives": [
        {
          "timestamps": [
            [
              "learn", 
              1.29, 
              1.75
            ], 
            [
              "all", 
              1.96, 
              2.16
            ], 
            [
              "were", 
              2.16, 
              2.51
            ]
          ], 
          "confidence": 0.437, 
          "transcript": "learn all were "
        }
      ], 
      "final": true
    }, 
    {
      "alternatives": [
        {
          "timestamps": [
            [
              "yes", 
              8.95, 
              9.2
            ], 
            [
              "you", 
              9.2, 
              9.29
            ], 
            [
              "decision", 
              9.29, 
              9.8
            ], 
            [
              "back", 
              10.13, 
              10.49
            ], 
            [
              "to", 
              10.52, 
              10.67
            ], 
            [
              "school", 
              10.67, 
              11.3
            ], 
            [
              "B.", 
              11.63, 
              12.0
            ], 
            [
              "A.", 
              12.0, 
              12.31
            ], 
            [
              "C.", 
              12.31, 
              12.7
            ], 
            [
              "K.", 
              12.7, 
              13.25
            ], 
            [
              "back", 
              13.35, 
              13.86
            ], 
            [
              "S.", 
              14.16, 
              14.54
            ], 
            [
              "C.", 
              14.57, 
              14.89
            ], 
            [
              "H.", 
              14.89, 
              15.27
            ], 
            [
              "O.", 
              15.3, 
              15.71
            ], 
            [
              "L.", 
              15.71, 
              16.15
            ], 
            [
              "school", 
              16.2, 
              16.87
            ], 
            [
              "back", 
              17.21, 
              17.67
            ], 
            [
              "to", 
              17.71, 
              17.89
            ], 
            [
              "school", 
              17.89, 
              18.52
            ], 
            [
              "back", 
              18.88, 
              19.21
            ], 
            [
              "to", 
              19.21, 
              19.46
            ], 
            [
              "school", 
              19.46, 
              19.96
            ], 
            [
              "final", 
              19.99, 
              20.37
            ], 
            [
              "wishes", 
              20.37, 
              20.76
            ], 
            [
              "shop", 
              20.76, 
              21.05
            ], 
            [
              "teach", 
              21.14, 
              21.52
            ], 
            [
              "it", 
              21.52, 
              21.72
            ], 
            [
              "to", 
              21.72, 
              21.82
            ], 
            [
              "reduce", 
              21.82, 
              22.24
            ], 
            [
              "chatty", 
              22.24, 
              22.8
            ], 
            [
              "issue", 
              22.8, 
              23.15
            ], 
            [
              "your", 
              23.18, 
              23.39
            ], 
            [
              "case", 
              23.39, 
              23.72
            ], 
            [
              "yet", 
              23.72, 
              23.95
            ], 
            [
              "not", 
              23.95, 
              24.13
            ], 
            [
              "many", 
              24.42, 
              24.71
            ], 
            [
              "stores", 
              24.71, 
              25.26
            ], 
            [
              "have", 
              25.26, 
              25.63
            ], 
            [
              "back", 
              25.63, 
              25.86
            ], 
            [
              "to", 
              25.86, 
              25.98
            ], 
            [
              "school", 
              25.98, 
              26.31
            ], 
            [
              "promotions", 
              26.31, 
              26.94
            ], 
            [
              "in", 
              26.97, 
              27.17
            ], 
            [
              "August", 
              27.17, 
              27.73
            ], 
            [
              "conclusion", 
              27.92, 
              28.51
            ], 
            [
              "the", 
              28.51, 
              28.61
            ], 
            [
              "handle", 
              28.61, 
              28.89
            ], 
            [
              "with", 
              28.89, 
              29.03
            ], 
            [
              "that", 
              29.03, 
              29.2
            ], 
            [
              "body", 
              29.2, 
              29.47
            ], 
            [
              "of", 
              29.47, 
              29.6
            ], 
            [
              "encentuate", 
              29.6, 
              30.36
            ], 
            [
              "to", 
              30.36, 
              30.48
            ], 
            [
              "catia", 
              30.48, 
              30.89
            ], 
            [
              "GCN", 
              30.89, 
              31.48
            ], 
            [
              "two", 
              31.86, 
              32.07
            ], 
            [
              "champagne", 
              32.07, 
              32.58
            ], 
            [
              "to", 
              32.61, 
              32.84
            ], 
            [
              "show", 
              32.84, 
              33.06
            ], 
            [
              "for", 
              33.06, 
              33.3
            ], 
            [
              "the", 
              33.3, 
              33.46
            ], 
            [
              "students", 
              33.86, 
              34.36
            ], 
            [
              "need", 
              34.36, 
              34.59
            ], 
            [
              "to", 
              34.59, 
              34.69
            ], 
            [
              "buy", 
              34.69, 
              34.94
            ], 
            [
              "school", 
              34.94, 
              35.35
            ], 
            [
              "supplies", 
              35.35, 
              36.05
            ], 
            [
              "according", 
              36.11, 
              36.57
            ], 
            [
              "to", 
              36.57, 
              36.71
            ], 
            [
              "the", 
              36.71, 
              36.85
            ], 
            [
              "back", 
              36.85, 
              37.09
            ], 
            [
              "to", 
              37.09, 
              37.22
            ], 
            [
              "school", 
              37.22, 
              37.56
            ], 
            [
              "list", 
              37.56, 
              38.1
            ], 
            [
              "Chechen", 
              38.38, 
              38.75
            ], 
            [
              "male", 
              38.75, 
              39.02
            ], 
            [
              "Confucius", 
              39.02, 
              39.73
            ], 
            [
              "outlaw", 
              39.73, 
              39.97
            ], 
            [
              "shoe", 
              39.97, 
              40.25
            ], 
            [
              "father", 
              40.25, 
              40.57
            ], 
            [
              "dances", 
              40.57, 
              41.01
            ], 
            [
              "to", 
              41.12, 
              41.29
            ], 
            [
              "call", 
              41.29, 
              41.47
            ], 
            [
              "my", 
              41.47, 
              41.65
            ], 
            [
              "shoes", 
              41.65, 
              41.98
            ], 
            [
              "you", 
              41.98, 
              42.13
            ], 
            [
              "won't", 
              42.13, 
              42.32
            ], 
            [
              "you", 
              42.32, 
              42.53
            ], 
            [
              "so", 
              42.87, 
              43.26
            ], 
            [
              "have", 
              43.29, 
              43.51
            ], 
            [
              "you", 
              43.51, 
              43.68
            ], 
            [
              "done", 
              43.68, 
              43.96
            ], 
            [
              "your", 
              43.96, 
              44.36
            ], 
            [
              "back", 
              44.36, 
              44.6
            ], 
            [
              "to", 
              44.6, 
              44.71
            ], 
            [
              "school", 
              44.71, 
              45.01
            ], 
            [
              "shopping", 
              45.01, 
              45.43
            ], 
            [
              "yet", 
              45.43, 
              45.69
            ], 
            [
              "nemeses", 
              45.96, 
              46.52
            ], 
            [
              "to", 
              46.52, 
              46.66
            ], 
            [
              "teach", 
              46.66, 
              46.97
            ], 
            [
              "other", 
              46.97, 
              47.21
            ], 
            [
              "committee", 
              47.21, 
              47.71
            ], 
            [
              "neat", 
              47.85, 
              48.17
            ], 
            [
              "though", 
              48.17, 
              48.27
            ], 
            [
              "my", 
              48.27, 
              48.5
            ], 
            [
              "two", 
              48.5, 
              48.77
            ], 
            [
              "anima", 
              48.77, 
              49.21
            ]
          ], 
          "confidence": 0.716, 
          "transcript": "yes you decision back to school B. A. C. K. back S. C. H. O. L. school back to school back to school final wishes shop teach it to reduce chatty issue your case yet not many stores have back to school promotions in August conclusion the handle with that body of encentuate to catia GCN two champagne to show for the students need to buy school supplies according to the back to school list Chechen male Confucius outlaw shoe father dances to call my shoes you won't you so have you done your back to school shopping yet nemeses to teach other committee neat though my two anima "
        }
      ], 
      "final": true
    }, 
    {
      "alternatives": [
        {
          "timestamps": [
            [
              "how", 
              49.78, 
              50.08
            ], 
            [
              "did", 
              50.29, 
              50.44
            ], 
            [
              "your", 
              50.44, 
              50.56
            ], 
            [
              "mission", 
              50.56, 
              50.84
            ], 
            [
              "is", 
              50.84, 
              50.94
            ], 
            [
              "to", 
              50.94, 
              51.02
            ], 
            [
              "this", 
              51.02, 
              51.21
            ], 
            [
              "issue", 
              51.21, 
              51.51
            ], 
            [
              "back", 
              51.86, 
              52.13
            ], 
            [
              "to", 
              52.17, 
              52.33
            ], 
            [
              "school", 
              52.33, 
              52.87
            ]
          ], 
          "confidence": 0.718, 
          "transcript": "how did your mission is to this issue back to school "
        }
      ], 
      "final": true
    }, 
    {
      "alternatives": [
        {
          "timestamps": [
            [
              "back", 
              53.4, 
              53.64
            ], 
            [
              "to", 
              53.7, 
              53.85
            ], 
            [
              "school", 
              53.85, 
              54.34
            ]
          ], 
          "confidence": 0.996, 
          "transcript": "back to school "
        }
      ], 
      "final": true
    }, 
    {
      "alternatives": [
        {
          "timestamps": [
            [
              "back", 
              55.06, 
              55.34
            ], 
            [
              "to", 
              55.44, 
              55.6
            ], 
            [
              "school", 
              55.6, 
              55.96
            ]
          ], 
          "confidence": 0.999, 
          "transcript": "back to school "
        }
      ], 
      "final": true
    }
  ], 
  "result_index": 0
}
'''
print(type(str1))
import re,jsonpath,json
re_trans = re.compile(r'"transcript":.*?}',re.S)
text_list = re.findall(re_trans,str1)
print(text_list)
re_transcript = re.compile(r'"transcript": "(.*)?"')
text_list_new = []
for i in text_list:
    text = re.search(re_transcript,i)
    if text:
        text = text.group(1)
        text_list_new.append(text)
text = ','.join(text_list_new)
print(text)
    # i = i.replace('"transcript": "','')
    # i = i.replace('}','')
    # i = i.replace('\\n','')
    # i = i.replace('"','')
    # print(text)


str1 = '\u0645\u0631\u062d\u0628\u0627 \u0628\u0643\u0645 \u0641\u064a \u062e\u062f\u0645\u0627\u062a'
print str1.decode('unicode_escape')
zh = '\u5443 \u6c83\u5c14 ,\u4eca\u5929 \u6211\u4eec\u8981 \u5b66 \u7684 \u6b64\u4e8b \u5f85 \u5c31\u662f'
print zh.decode('unicode_escape')
